# Generated by Django 4.1.6 on 2023-02-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='offset',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='type_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
