# Generated by Django 4.1.6 on 2023-02-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_food_offset_alter_food_total_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.food'),
        ),
    ]
