# Generated by Django 4.1.6 on 2023-02-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_products_related_id_alter_products_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='related_id',
        ),
    ]
