# Generated by Django 4.1.6 on 2023-02-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_food_type_id_products_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='type_id',
            new_name='food',
        ),
    ]
