# Generated by Django 4.1.6 on 2023-02-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_food_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='api.food'),
        ),
    ]
