# Generated by Django 4.1.6 on 2023-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_products_food_products_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
    ]
