# Generated by Django 4.1.6 on 2023-03-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
